name:  Materials Informatics Class
markdown: kramdown
input: GFM
url: http://materials-informatics-class-fall2014.github.io/
description:  Fall 2014 Class Project Publication Index


permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
